# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.


In [1]:
# Exercise 1

import numpy as np

array_1_to_10 = np.arange(1, 11)
print("NumPy array from 1 to 10:", array_1_to_10)


NumPy array from 1 to 10: [ 1  2  3  4  5  6  7  8  9 10]



---

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.


In [3]:
# Exercise 2
zeros_array = np.zeros((3, 3))
print("3x3 array filled with zeros:\n", zeros_array)


3x3 array filled with zeros:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]



---

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.


In [4]:
# Exercise 3

evenly_spaced = np.linspace(0, 5, 10)
print("10 evenly spaced numbers between 0 and 5:\n", evenly_spaced)


10 evenly spaced numbers between 0 and 5:
 [0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]



---

### Exercise 4:
Create a 5x5 identity matrix using NumPy.


In [5]:
# Exercise 4
identity_matrix = np.eye(5)
print("5x5 Identity matrix:\n", identity_matrix)

5x5 Identity matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]



---

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.


In [6]:
# Exercise 5

random_matrix = np.random.rand(4, 4)
print("4x4 matrix with random values:\n", random_matrix)


4x4 matrix with random values:
 [[0.69013737 0.7067195  0.45922156 0.20996165]
 [0.78333853 0.38111015 0.15828578 0.34127559]
 [0.11064385 0.50324888 0.16941807 0.7211502 ]
 [0.27813448 0.57683747 0.92464295 0.04157935]]



---

### Exercise 6:
Find the shape of a NumPy array.


In [7]:
# Exercise 6
array_example = np.array([[1, 2, 3], [4, 5, 6]])
print("Array:\n", array_example)
print("Shape of the array:", array_example.shape)


Array:
 [[1 2 3]
 [4 5 6]]
Shape of the array: (2, 3)



---

### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.


In [8]:
# Exercise 7
array_1d = np.arange(16)
reshaped_array = array_1d.reshape(4, 4)
print("Reshaped 4x4 array:\n", reshaped_array)


Reshaped 4x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]



---

### Exercise 8:
Find the data type of the elements in a NumPy array.


In [10]:
# Exercise 8
datatype_array = np.array([1, 2, 3])
print("Data type of the array elements:", datatype_array.dtype)


Data type of the array elements: int32



---

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.


In [11]:
# Exercise 9
array_1_to_100 = np.arange(1, 101)
even_numbers = array_1_to_100[array_1_to_100 % 2 == 0]
print("Even numbers from 1 to 100:\n", even_numbers)


Even numbers from 1 to 100:
 [  2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34  36
  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70  72
  74  76  78  80  82  84  86  88  90  92  94  96  98 100]



---

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.


In [12]:
# Exercise 10
random_integers = np.random.randint(10, 51, size=(6, 6))
print("6x6 matrix of random integers between 10 and 50:\n", random_integers)


6x6 matrix of random integers between 10 and 50:
 [[17 35 50 48 38 15]
 [25 24 48 24 40 48]
 [37 20 21 16 32 29]
 [18 10 38 27 22 18]
 [38 32 18 19 29 11]
 [49 25 22 24 23 40]]



---

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.


In [13]:
# Exercise 11
# Exercise 11
original_matrix = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 matrix:\n", original_matrix)

submatrix = original_matrix[1:4, 1:4]  # rows 1 to 3 and columns 1 to 3
print("Extracted submatrix (3x3):\n", submatrix)

Original 5x5 matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Extracted submatrix (3x3):
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]



---

### Exercise 12:
Calculate the sum of all elements in a NumPy array.


In [14]:
# Exercise 12

sum_array = np.array([[1, 2], [3, 4]])
total_sum = np.sum(sum_array)
print("Sum of all elements in the array:", total_sum)


Sum of all elements in the array: 10



---

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.


In [15]:
# Exercise 13

array_sample = np.array([5, 10, 15, 20, 25])
max_value = np.max(array_sample)
min_value = np.min(array_sample)

print("Maximum value:", max_value)
print("Minimum value:", min_value)


Maximum value: 25
Minimum value: 5



---

### Exercise 14:
Find the maximum and minimum values in a NumPy array.


In [16]:
# Exercise 14
data = np.array([1, 2, 3, 4, 5, 6])

mean_val = np.mean(data)
median_val = np.median(data)
std_dev = np.std(data)

print("Mean:", mean_val)
print("Median:", median_val)
print("Standard Deviation:", std_dev)


Mean: 3.5
Median: 3.5
Standard Deviation: 1.707825127659933



---

### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.


In [17]:
# Exercise 15
def is_multiple_of_10(number):
    return number % 10 == 0

# Example usage
num = 30
if is_multiple_of_10(num):
    print(f"{num} is a multiple of 10.")
else:
    print(f"{num} is NOT a multiple of 10.")


30 is a multiple of 10.



---

### Exercise 16:
Create a NumPy array and reverse its elements.


In [18]:
# Exercise 16
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)


Reversed array: [5 4 3 2 1]



---

### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.


In [19]:
# Exercise 17
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
result = a * b
print("Element-wise multiplication:\n", result)


Element-wise multiplication:
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]



---

### Exercise 18:
Create a diagonal matrix from a given 1D array.


In [20]:
# Exercise 18
arr = np.array([10, 20, 30])
diag_matrix = np.diag(arr)
print("Diagonal matrix:\n", diag_matrix)


Diagonal matrix:
 [[10  0  0]
 [ 0 20  0]
 [ 0  0 30]]



---

### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.


In [21]:
# Exercise 19
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
product = np.dot(A, B)
print("Matrix multiplication result:\n", product)


Matrix multiplication result:
 [[19 22]
 [43 50]]



---

### Exercise 20:
Flatten a 2D NumPy array into a 1D array.


In [22]:
# Exercise 20
matrix = np.array([[1, 2], [3, 4]])
flattened = matrix.flatten()
print("Flattened array:", flattened)


Flattened array: [1 2 3 4]



---

### Exercise 21:
Stack two NumPy arrays vertically.


In [23]:
# Exercise 21
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vstacked = np.vstack((a, b))
print("Vertically stacked:\n", vstacked)


Vertically stacked:
 [[1 2 3]
 [4 5 6]]



---

### Exercise 22:
Stack two NumPy arrays horizontally.


In [24]:
# Exercise 22
hstacked = np.hstack((a, b))
print("Horizontally stacked:\n", hstacked)


Horizontally stacked:
 [1 2 3 4 5 6]



---

### Exercise 23:
Split a NumPy array into multiple sub-arrays.


In [25]:
# Exercise 23
arr = np.array([1, 2, 3, 4, 5, 6])
split_arr = np.split(arr, 3)
print("Split arrays:", split_arr)


Split arrays: [array([1, 2]), array([3, 4]), array([5, 6])]



---

### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.


In [26]:
# Exercise 24
random_array = np.random.rand(3, 3)
rounded = np.round(random_array, 2)
print("Rounded array:\n", rounded)


Rounded array:
 [[0.77 0.96 0.66]
 [0.76 0.45 0.87]
 [0.27 0.97 0.13]]



---

### Exercise 25:
Find the unique elements of a NumPy array.


In [27]:
# Exercise 25
arr = np.array([1, 2, 2, 3, 4, 4, 5])
unique_elements = np.unique(arr)
print("Unique elements:", unique_elements)


Unique elements: [1 2 3 4 5]



---

### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.


In [28]:
# Exercise 26
arr = np.array([2, 5, 1, 8, 0])
arr[arr < 3] = 3
print("Modified array:", arr)


Modified array: [3 5 3 8 3]



---

### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.


In [29]:
# Exercise 27
arr = np.array([1, 2, 3, 4])
cumsum = np.cumsum(arr)
print("Cumulative sum:", cumsum)

Cumulative sum: [ 1  3  6 10]



---

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.


In [30]:
# Exercise 28
arr = np.array([0, 1, 2, 0, 3])
nonzeros = np.count_nonzero(arr)
print("Number of non-zero elements:", nonzeros)


Number of non-zero elements: 3



---

### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.


In [31]:
# Exercise 29
arr = np.random.randint(0, 100, size=10)
sorted_arr = np.sort(arr)
print("Sorted array:", sorted_arr)


Sorted array: [ 4  8 11 20 43 71 73 79 80 95]



---

### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.


In [32]:
# Exercise 30
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_sum = matrix.sum(axis=1)
col_sum = matrix.sum(axis=0)
print("Row-wise sum:", row_sum)
print("Column-wise sum:", col_sum)


Row-wise sum: [ 6 15 24]
Column-wise sum: [12 15 18]



---

### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).


In [33]:
# Exercise 31
arr = np.random.rand(3, 3) * 100
normalized = (arr - arr.min()) / (arr.max() - arr.min())
print("Normalized array:\n", normalized)


Normalized array:
 [[0.91972201 0.9111729  0.88771062]
 [0.77048217 0.         0.95529754]
 [1.         0.0726544  0.11523474]]



---

### Exercise 32:
Create two NumPy arrays and find the dot product.


In [34]:
# Exercise 32
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
dot_product = np.dot(a, b)
print("Dot product:", dot_product)


Dot product: 32



---

### Exercise 33:
Find the trace of a square NumPy matrix.


In [36]:
# Exercise 33
matrix = np.array([[1, 2], [3, 4]])
trace = np.trace(matrix)
print("Trace of matrix:", trace)


Trace of matrix: 5



---

### Exercise 34:
Create a 2D array and swap two rows.


In [35]:
# Exercise 34
arr = np.array([[1, 2], [3, 4]])
arr[[0, 1]] = arr[[1, 0]]
print("Array after swapping rows:\n", arr)


Array after swapping rows:
 [[3 4]
 [1 2]]



---

### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.


In [37]:
# Exercise 35
arr = np.array([1, 2, 3])
column_vector = arr.reshape(-1, 1)
print("Column vector:\n", column_vector)


Column vector:
 [[1]
 [2]
 [3]]



---

### Exercise 36:
Find the determinant of a 3x3 matrix.


In [38]:
# Exercise 36
matrix = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
det = np.linalg.det(matrix)
print("Determinant:", det)


Determinant: 0.9999999999999987



---

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.


In [39]:
# Exercise 37
matrix = np.array([[2, 1], [1, 2]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Eigenvalues: [3. 1.]
Eigenvectors:
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]



---

### Exercise 38:
Solve a system of linear equations using NumPy.


In [40]:
# Exercise 38
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
solution = np.linalg.solve(A, b)
print("Solution (x, y):", solution)


Solution (x, y): [2. 3.]



---

### Exercise 39:
Add Gaussian noise to a NumPy array.


In [41]:
# Exercise 39
arr = np.array([10, 20, 30])
noise = np.random.normal(0, 1, arr.shape)
noisy_arr = arr + noise
print("Array with Gaussian noise:", noisy_arr)


Array with Gaussian noise: [11.28401972 21.76199589 29.56469012]



---

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.


In [42]:
# Exercise 40
matrix = np.arange(1, 17).reshape(4, 4)
diagonal = np.diag(matrix)
print("Diagonal elements:", diagonal)


Diagonal elements: [ 1  6 11 16]



---

### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.


In [43]:
# Exercise 41
arr = np.random.randint(0, 100, size=100)
clipped = np.clip(arr, 10, 50)
print("Clipped array:\n", clipped)


Clipped array:
 [34 36 30 50 50 50 47 50 30 16 17 27 30 50 50 28 50 50 16 50 50 19 50 10
 10 50 10 10 10 50 50 31 10 19 46 50 50 50 34 50 37 50 46 50 10 40 50 50
 10 10 41 50 50 34 50 30 17 36 21 44 20 46 36 50 50 10 13 10 50 50 50 24
 50 10 38 50 50 16 18 50 50 50 50 50 50 50 30 50 50 10 50 50 22 11 50 50
 23 21 11 50]



---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.


In [44]:
# Exercise 42
arr = np.array([[1, -2, 3], [-4, 5, -6]])
arr[arr < 0] = 0
print("Array with negatives replaced:\n", arr)


Array with negatives replaced:
 [[1 0 3]
 [0 5 0]]



---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.


In [45]:
# Exercise 43
a = np.array([1, 2])
b = np.array([3, 4])
inner = np.inner(a, b)
outer = np.outer(a, b)
print("Inner product:", inner)
print("Outer product:\n", outer)


Inner product: 11
Outer product:
 [[3 4]
 [6 8]]



---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.


In [46]:
# Exercise 44
from scipy.spatial.distance import pdist, squareform

points = np.array([[0, 0], [1, 1], [2, 2]])
pairwise_dist = squareform(pdist(points))
print("Pairwise distances:\n", pairwise_dist)


Pairwise distances:
 [[0.         1.41421356 2.82842712]
 [1.41421356 0.         1.41421356]
 [2.82842712 1.41421356 0.        ]]



---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.


In [47]:
# Exercise 45
data = np.array([
    ('Alice', 25, 5.5),
    ('Bob', 30, 6.0)
], dtype=[('name', 'U10'), ('age', 'i4'), ('height', 'f4')])

print("Structured array:", data)


Structured array: [('Alice', 25, 5.5) ('Bob', 30, 6. )]



---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.


In [48]:
# Exercise 46
arr = np.random.randint(0, 10, size=(5, 5))
unique, counts = np.unique(arr, return_counts=True)
print("Matrix:\n", arr)
print("Value counts:", dict(zip(unique, counts)))


Matrix:
 [[1 1 0 6 4]
 [5 2 5 9 9]
 [7 9 5 2 6]
 [1 0 7 0 4]
 [6 1 1 0 4]]
Value counts: {0: 4, 1: 5, 2: 2, 4: 3, 5: 3, 6: 3, 7: 2, 9: 3}



---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.


In [49]:
# Exercise 47
arr = np.random.rand(3, 3)
row_means = arr.mean(axis=1, keepdims=True)
centered = arr - row_means
print("Original array:\n", arr)
print("Row-centered array:\n", centered)


Original array:
 [[0.29592777 0.80738858 0.69054129]
 [0.05380689 0.25714336 0.91134106]
 [0.29227058 0.14022042 0.19880751]]
Row-centered array:
 [[-0.30202478  0.20943603  0.09258875]
 [-0.35362355 -0.15028708  0.50391062]
 [ 0.08183774 -0.07021241 -0.01162533]]



---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.


In [50]:
# Exercise 48
arr = np.random.randint(0, 100, size=10)
condition = np.any(arr > 50)
print("Array:", arr)
print("Any value > 50:", condition)


Array: [37 79  2 71  7 24 54 79 89 19]
Any value > 50: True



---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.


In [51]:
# Exercise 49
arr = np.array([1, 2, 3, 4, 5])
window_size = 3
moving_avg = np.convolve(arr, np.ones(window_size)/window_size, mode='valid')
print("Moving average:", moving_avg)


Moving average: [2. 3. 4.]



---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.


In [52]:
# Exercise 50
a = np.array([1, 2, 3, 4])
b = np.array([4, 3, 2, 1])
correlation = np.corrcoef(a, b)[0, 1]
print("Pearson correlation coefficient:", correlation)


Pearson correlation coefficient: -1.0



---

### Exercise 51:
Convert a NumPy array of radians to degrees.


In [53]:
# Exercise 51
radians = np.array([0, np.pi/2, np.pi])
degrees = np.degrees(radians)
print("Degrees:", degrees)


Degrees: [  0.  90. 180.]



---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.


In [54]:
# Exercise 52
arr = np.random.rand(10)
variance = np.var(arr)
std_dev = np.std(arr)
print("Variance:", variance)
print("Standard Deviation:", std_dev)


Variance: 0.04604343507582005
Standard Deviation: 0.21457734054606056



---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.


In [55]:
# Exercise 53
arr = np.random.rand(3, 3)
row_max_indices = np.argmax(arr, axis=1)
col_max_indices = np.argmax(arr, axis=0)
print("Array:\n", arr)
print("Row max indices:", row_max_indices)
print("Column max indices:", col_max_indices)


Array:
 [[0.32757071 0.88793291 0.0909148 ]
 [0.53631535 0.71461857 0.23022324]
 [0.64140895 0.97749694 0.72847102]]
Row max indices: [1 1 1]
Column max indices: [2 2 2]



---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.


In [57]:
# Exercise 54
import numpy as np

# Define a 2x2 matrix
matrix = np.array([[1, 2],
                   [3, 4]])

# Compute the inverse
inverse_matrix = np.linalg.inv(matrix)

print("Original matrix:\n", matrix)
print("Inverse matrix:\n", inverse_matrix)



Original matrix:
 [[1 2]
 [3 4]]
Inverse matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]



---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).


In [58]:
# Exercise 55
arr = np.random.rand(10)
standardized = (arr - np.mean(arr)) / np.std(arr)
print("Standardized array:", standardized)


Standardized array: [ 0.55772162  0.67771641 -1.1066152  -0.72480399  1.40006985 -0.65454941
 -1.50010272 -0.6890691   0.64172654  1.397906  ]



---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.


In [59]:
# Exercise 56
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
add = a + b
sub = a - b
print("Addition:", add)
print("Subtraction:", sub)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]



---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.


In [60]:
# Exercise 57
arr = np.random.rand(10)
max_index = np.argmax(arr)
print("Array:", arr)
print("Index of max element:", max_index)


Array: [0.06621689 0.24570458 0.75278586 0.00628653 0.89252064 0.98666889
 0.49604935 0.55132563 0.75307466 0.91439707]
Index of max element: 5



---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.


In [61]:
# Exercise 58
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
rotated = np.rot90(arr)
print("Rotated 90 degrees:\n", rotated)


Rotated 90 degrees:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]



---

### Exercise 59:
Compute the Frobenius norm of a matrix.


In [62]:
# Exercise 59
matrix = np.array([[1, 2], [3, 4]])
frobenius_norm = np.linalg.norm(matrix, 'fro')
print("Frobenius norm:", frobenius_norm)


Frobenius norm: 5.477225575051661



---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.


In [64]:
# Exercise 60
arr = np.arange(27).reshape(3, 3, 3)
subarray = arr[1:, :, :2]
print("A 3D array slice:\n", subarray)


A 3D array slice:
 [[[ 9 10]
  [12 13]
  [15 16]]

 [[18 19]
  [21 22]
  [24 25]]]



---